<a target="_blank" href="https://colab.research.google.com/github/peterhgruber/python-intro-colab/blob/main/05Python_Dataframes.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Introduction to Python
### Main concepts of Python – Part 05
Peter Gruber (peter.gruber@usi.ch), 2024-04-01

* Pandas DataFrames

##  Pandas
- A powerful library for ...
    - Managing tabular data
    - Transforming data (filter, subset, merge, reshape)
    - Performing exploratory data analysis
    - Creating simple plots
- The standard library for data analysis in Python<br><br>


### Pandas DataFrames
- Natural structure for tabular (cross-sectional) data
  - Each row represents one observation (or record)
  - Each column represents one variable (or feature)
    - Variables of different types can be combined into a dataframe

## 0 Install Pandas

* May not be needed   
* Many environments come with Pandas pre-installed

In [ ]:
# Install pandas: Uncomment the line below and run it *once*
# !pip install pandas

## 1 Loading Pandas

* We would expect `import pandas`
* However *almost everybody* uses `import pandas as pd`
* This creates a shortcut – we will use `pd` for Pandas

In [9]:
# Importing the library
# "... as pd" creates a shortcut for later use ... everybody does it
import pandas as pd

## 2 Load data

- Synthetic dataset of student performance
  - See here for details: https://github.com/peterhgruber/python-intro-colab/blob/main/data/README.md

In [11]:
# Load dataframe
# For teaching purposes, we load the data directly from GitHub
# Later, you will need to provide the dataset in the right place

student = pd.read_csv('https://raw.githubusercontent.com/peterhgruber/python-intro-colab/main/data/student.csv')

❗️**Naming:** In this notebook, we have chosen to name the dataframe `student`, similar to the data file. Many people just name their dataframe `df`. This is OK as long as there is only **one** dataframe. Naming multiple dataframes `df`, `df2, … will surely lead to confusion.

## 3 Inspect data

* First steps in any data analysis
* *Note:* Python starts counting at 0 also with DataFrames

In [13]:
# Typing the name of any variable shows its contents
# In colab: try the blue "table button" right next to the column headings
student

      id  isMale  isCity  math  stat  econ   art  engl
0      1       0       1  95.3    82  73.6  86.5  68.6
1      2       0       0  53.7    63  81.0  38.7  38.9
2      3       0       0  62.0    74  74.1  52.5  55.1
3      4       1       0  22.2    59  35.2  74.9  84.5
4      5       1       0  76.0    86  72.7  66.2  64.4
..   ...     ...     ...   ...   ...   ...   ...   ...
205  206       1       0  58.3    82  83.9  51.8  60.7
206  207       1       1  66.3    93  92.2  68.6  56.1
207  208       1       0  50.9    71  64.0  32.7  49.9
208  209       0       0  57.5    56  72.2  59.1  61.0
209  210       0       0  76.6    56  90.5  62.8  51.4

[210 rows x 8 columns]

In [14]:
# First `n` entries (rows) of the dataframe
student.head(4)

   id  isMale  isCity  math  stat  econ   art  engl
0   1       0       1  95.3    82  73.6  86.5  68.6
1   2       0       0  53.7    63  81.0  38.7  38.9
2   3       0       0  62.0    74  74.1  52.5  55.1
3   4       1       0  22.2    59  35.2  74.9  84.5

In [15]:
# Last `n` entries (rows) of the dataframe
student.tail(3)

      id  isMale  isCity  math  stat  econ   art  engl
207  208       1       0  50.9    71  64.0  32.7  49.9
208  209       0       0  57.5    56  72.2  59.1  61.0
209  210       0       0  76.6    56  90.5  62.8  51.4

In [20]:
# Descriptive statistical summary
student.describe()

,id,isMale,isCity,math,stat,econ,art,engl
count,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
mean,105.500000,0.452381,0.400000,66.568095,70.385714,75.707143,60.070476,61.632381
std,60.765944,0.498917,0.491069,18.091878,15.922323,14.577097,18.418840,14.860902
min,1.000000,0.000000,0.000000,10.000000,15.000000,10.000000,19.000000,28.000000
25%,53.250000,0.000000,0.000000,55.150000,61.250000,68.350000,47.000000,50.225000
50%,105.500000,0.000000,0.000000,70.150000,73.500000,77.450000,59.550000,60.400000
75%,157.750000,1.000000,1.000000,79.400000,81.000000,85.850000,73.175000,72.050000
max,210.000000,1.000000,1.000000,98.000000,98.000000,100.800000,100.000000,100.000000

### 4 Subsetting

In [ ]:
# Select a column by name
student['Age']

In [ ]:
# *Select a column by index (rarely used)
student.iloc[:,2]

In [ ]:
# Select multiple columns
student[ ['Gender', 'EstimatedSalary'] ]

In [ ]:
# *Select a row by index
student.iloc[1,:]       #  (can leave out ",:" here)

In [ ]:
# Select multiple rows with colon
student.iloc[10:15,:]         # <-- upper index is "one more" (can leave out ",:" here)

In [ ]:
# Select multiple rows
student.iloc[[1, 67, 96],:]

In [ ]:
# Select individual element (rarely used)
# Salary of row 5
student.iloc[5,3]

### 5 Functions and summaries
* No need for complicated list comprehensions here
* Use `numpy` to apply function to entire vector
* Use `df.xxx()` methods to summarize data

In [ ]:
import numpy
numpy.log(student['EstimatedSalary'])

In [ ]:
# Average salary
student['EstimatedSalary'].mean()

In [ ]:
# Unique values in a column.
# Useful when analysing categories such as products, stocks, countries, etc
student['Gender'].unique()

In [ ]:
student['Age'] <= 40

In [ ]:
# Count number of young customers
sum(student['Age'] <= 40)

In [ ]:
# Fraction of young customers
(student['Age'] <= 40).mean()

### *5.1 Multiple and complementary conditons .. not that easy

- Pandas is an abstraction that simplifies data operations, but...
    - Has different Object Types: Series and DataFrame
    - Requires specific syntax (`~`, `&`,  `|`) instead of  `not`, `and`, `or`.

In [ ]:
# A "DataFrame" object
print(type(student))

# Single column is seen as "Series" object
print(type(student['Age']))

# Multiple columns are seen as "DataFrame" object
print(type(student[ ['Age', 'Purchased'] ]))

In [ ]:
# Complementary conditon, "~" for "not"
~(student['Age'] <=40)

In [ ]:
# Dual conditions, "&" for "and"
# Users with age below 40 and salary above 50'000
(student['Age']<=40) & (student['EstimatedSalary']>=50000)

In [ ]:
# "|" for "or"
# Users with age either under 30 or above 45
(student['Age']<=30) | (student['Age']>=45)

In [ ]:
# Fraction of people above 40
( ~(student['Age']<=40) ).mean()

In [ ]:
# Tertia non datur
( ~(student['Age']<=40) ).mean() + (student['Age']<=40).mean()

### 6 Subsetting by condition

* Daily bread of data scientist. Analyze ...
    * "all older participants"
    * "all older male participants"
    * "all older male participants with high income"
* **Syntax:** `df[<condition> ]`
* **Syntax:** `df['<column>'][<condition> ]`

In [ ]:
# Recap
student['Age']>=30

In [ ]:
# Select rows for which <condtion> is True
student[ student['Age']>=30 ]

In [ ]:
# Subset just one column
student['EstimatedSalary'][ student['Age']>=30 ]

**Notice:** Length is now shorter

In [ ]:
# Statistics of a subset
# Average salary of people aged 30 or more.
student['EstimatedSalary'][ student['Age']>=30 ].mean()

#### 6.1 Multiple conditions
* Require extra `()` around condition
* Still `&` and `|` operators
* **Syntax** `df['<column>'][ (<condition1>) & (<condition2>) ]`

In [ ]:
student['EstimatedSalary'][ (student['Age']>=30) & (student['Gender']=="Male") ].mean()

In [ ]:
student['EstimatedSalary'][ (student['Age']>=30) & (student['Gender']=="Male") &
                       (student['EstimatedSalary']>40000) ].mean()

**Exercise:** Answer these questions ...
* Is the average salary for male or female participants higher?
* What is the average salary

In [ ]:
student['EstimatedSalary'][ student['Gender']=="Male" ].mean()

In [ ]:
student['EstimatedSalary'][ ~(student['Gender']=="Male") ].mean()

In [ ]:
student['EstimatedSalary'].mean()

## 7 Modify dataframe structure
- Add new column: simply assign values
- Delete a column: `df.drop('<column>')`

In [ ]:
retirement_age = 60
student['YearsToRetirement'] = retirement_age - student['Age']
student

In [ ]:
# Remove column
student.drop(columns='YearsToRetirement', inplace=True)

In [ ]:
student

**Exercise:** Add a column named `SalaryUSD` that convertes the salary from CHF to USD. The exchange rate is 1.15 USD/CHF.

In [ ]:
# code goes here
student['SalaryUSD'] = student['EstimatedSalary']*1.15

In [ ]:
student

## *8 Exporting to LaTeX

* Writing LaTeX tables can be tedious
* Pandas lets you export a DataFrame to the LaTeX table format
* **However,** often we don't want to export the data itself, but rather a statistical summary $\rightarrow$ this requires one extra step

In [22]:
# Recall
student.describe()

,id,isMale,isCity,math,stat,econ,art,engl
count,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
mean,105.500000,0.452381,0.400000,66.568095,70.385714,75.707143,60.070476,61.632381
std,60.765944,0.498917,0.491069,18.091878,15.922323,14.577097,18.418840,14.860902
min,1.000000,0.000000,0.000000,10.000000,15.000000,10.000000,19.000000,28.000000
25%,53.250000,0.000000,0.000000,55.150000,61.250000,68.350000,47.000000,50.225000
50%,105.500000,0.000000,0.000000,70.150000,73.500000,77.450000,59.550000,60.400000
75%,157.750000,1.000000,1.000000,79.400000,81.000000,85.850000,73.175000,72.050000
max,210.000000,1.000000,1.000000,98.000000,98.000000,100.800000,100.000000,100.000000

In [23]:
# To export the above output to LaTeX, we need to create
# a second DataFrame called student_summary
student_summary = student.describe()
student_summary

,id,isMale,isCity,math,stat,econ,art,engl
count,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
mean,105.500000,0.452381,0.400000,66.568095,70.385714,75.707143,60.070476,61.632381
std,60.765944,0.498917,0.491069,18.091878,15.922323,14.577097,18.418840,14.860902
min,1.000000,0.000000,0.000000,10.000000,15.000000,10.000000,19.000000,28.000000
25%,53.250000,0.000000,0.000000,55.150000,61.250000,68.350000,47.000000,50.225000
50%,105.500000,0.000000,0.000000,70.150000,73.500000,77.450000,59.550000,60.400000
75%,157.750000,1.000000,1.000000,79.400000,81.000000,85.850000,73.175000,72.050000
max,210.000000,1.000000,1.000000,98.000000,98.000000,100.800000,100.000000,100.000000

In [25]:
# Now we can export student_summary to LaTeX
student_summary.to_latex('student.tex')

***Formatting:** the `float_format` parameter controls the number of digits.

For example `'%.2f'` means *"2 decimal places"*.

In [27]:
student_summary.to_latex('student_2.tex', float_format='%.2f')

❓Where is the file?

* You find `student.tex` in the **Files** tab ![files.png]().
* Do not forget to download it!